apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "2"
    kubernetes.io/description: |
      This DaemonSet launches the ovn-kubernetes networking components for worker nodes.
  creationTimestamp: "2024-08-27T12:08:51Z"
  generation: 2
  name: ovnkube-node
  namespace: ovn-kubernetes
  resourceVersion: "601975"
  uid: 8304a683-e79a-4f17-84d5-425551fdbe57
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ovnkube-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ovnkube-node
        component: network
        kubernetes.io/os: linux
        name: ovnkube-node
        type: infra
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.ovn.org/dpu-host
                operator: DoesNotExist
              - key: k8s.ovn.org/dpu
                operator: DoesNotExist
      containers:
      - command:
        - /root/ovnkube.sh
        - ovn-node
        env:
        - name: OVN_DAEMONSET_VERSION
          value: 1.0.0
        - name: OVNKUBE_LOGLEVEL
          value: "5"
        - name: OVNKUBE_LOGFILE_MAXSIZE
          value: "100"
        - name: OVNKUBE_LOGFILE_MAXBACKUPS
          value: "5"
        - name: OVNKUBE_LOGFILE_MAXAGE
          value: "5"
        - name: OVN_NET_CIDR
          valueFrom:
            configMapKeyRef:
              key: net_cidr
              name: ovn-config
        - name: OVN_SVC_CIDR
          valueFrom:
            configMapKeyRef:
              key: svc_cidr
              name: ovn-config
        - name: K8S_APISERVER
          valueFrom:
            configMapKeyRef:
              key: k8s_apiserver
              name: ovn-config
        - name: OVN_MTU
          valueFrom:
            configMapKeyRef:
              key: mtu
              name: ovn-config
        - name: OVN_ROUTABLE_MTU
          valueFrom:
            configMapKeyRef:
              key: routable_mtu
              name: ovn-config
              optional: true
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: OVN_GATEWAY_MODE
          value: local
        - name: OVN_GATEWAY_OPTS
        - name: OVN_HYBRID_OVERLAY_ENABLE
        - name: OVN_ADMIN_NETWORK_POLICY_ENABLE
        - name: OVN_EGRESSIP_ENABLE
          value: "true"
        - name: OVN_EGRESSIP_HEALTHCHECK_PORT
        - name: OVN_EGRESSSERVICE_ENABLE
        - name: OVN_HYBRID_OVERLAY_NET_CIDR
        - name: OVN_DISABLE_SNAT_MULTIPLE_GWS
        - name: OVN_DISABLE_FORWARDING
        - name: OVN_ENCAP_PORT
        - name: OVN_DISABLE_PKT_MTU_CHECK
        - name: OVN_NETFLOW_TARGETS
        - name: OVN_SFLOW_TARGETS
        - name: OVN_IPFIX_TARGETS
        - name: OVN_IPFIX_SAMPLING
        - name: OVN_IPFIX_CACHE_MAX_FLOWS
        - name: OVN_IPFIX_CACHE_ACTIVE_TIMEOUT
        - name: OVN_V4_JOIN_SUBNET
        - name: OVN_V6_JOIN_SUBNET
        - name: OVN_V4_MASQUERADE_SUBNET
        - name: OVN_V6_MASQUERADE_SUBNET
        - name: OVN_MULTICAST_ENABLE
        - name: OVN_UNPRIVILEGED_MODE
          value: "no"
        - name: OVN_EX_GW_NETWORK_INTERFACE
        - name: OVN_ENABLE_OVNKUBE_IDENTITY
          value: "false"
        - name: OVN_SSL_ENABLE
          value: "no"
        - name: OVN_DISABLE_OVN_IFACE_ID_VER
          value: "false"
        - name: OVN_REMOTE_PROBE_INTERVAL
          value: "100000"
        - name: OVN_MONITOR_ALL
        - name: OVN_OFCTRL_WAIT_BEFORE_CLEAR
        - name: OVN_ENABLE_LFLOW_CACHE
        - name: OVN_LFLOW_CACHE_LIMIT
        - name: OVN_LFLOW_CACHE_LIMIT_KB
        - name: OVN_MULTI_NETWORK_ENABLE
        - name: OVN_NETWORK_SEGMENTATION_ENABLE
        - name: OVN_ENABLE_INTERCONNECT
        - name: OVN_ENABLE_MULTI_EXTERNAL_GATEWAY
        - name: OVNKUBE_NODE_MGMT_PORT_NETDEV
        - name: OVN_HOST_NETWORK_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: host_network_namespace
              name: ovn-config
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: registry.lab.syscallx86.com/ovn-daemonset-fedora:latest
        imagePullPolicy: IfNotPresent
        name: ovnkube-node
        readinessProbe:
          exec:
            command:
            - /usr/bin/ovn-kube-util
            - readiness-probe
            - -t
            - ovnkube-node
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /host
          name: host-slash
          readOnly: true
        - mountPath: /var/run/dbus/
          name: host-var-run-dbus
          readOnly: true
        - mountPath: /var/lib/kubelet
          name: host-kubelet
          readOnly: true
        - mountPath: /var/log/ovn-kubernetes/
          name: host-var-log-ovnkube
        - mountPath: /var/run/ovn-kubernetes
          name: host-var-run-ovn-kubernetes
        - mountPath: /opt/cni/bin
          name: host-opt-cni-bin
        - mountPath: /etc/cni/net.d
          name: host-etc-cni-netd
        - mountPath: /var/run/netns
          mountPropagation: Bidirectional
          name: host-netns
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        - mountPath: /var/run/ovn/
          name: host-var-run-ovs
        - mountPath: /ovn-cert
          name: host-ovn-cert
          readOnly: true
        - mountPath: /etc/openvswitch/
          name: host-etc-ovs
          readOnly: true
        - mountPath: /etc/ovn/
          name: host-var-lib-ovs
          readOnly: true
      - command:
        - /root/ovnkube.sh
        - ovn-controller
        env:
        - name: OVN_DAEMONSET_VERSION
          value: 1.0.0
        - name: OVN_LOGLEVEL_CONTROLLER
          value: -vconsole:dbg
        - name: K8S_APISERVER
          valueFrom:
            configMapKeyRef:
              key: k8s_apiserver
              name: ovn-config
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: OVN_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OVN_SSL_ENABLE
          value: "no"
        image: registry.lab.syscallx86.com/ovn-daemonset-fedora:latest
        imagePullPolicy: IfNotPresent
        name: ovn-controller
        readinessProbe:
          exec:
            command:
            - /usr/bin/ovn-kube-util
            - readiness-probe
            - -t
            - ovn-controller
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        securityContext:
          capabilities:
            add:
            - SYS_NICE
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/dbus/
          name: host-var-run-dbus
          readOnly: true
        - mountPath: /var/log/openvswitch/
          name: host-var-log-ovs
        - mountPath: /var/log/ovn/
          name: host-var-log-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        - mountPath: /var/run/ovn/
          name: host-var-run-ovs
        - mountPath: /ovn-cert
          name: host-ovn-cert
          readOnly: true
      - command:
        - /root/ovnkube.sh
        - ovs-metrics
        env:
        - name: OVN_DAEMONSET_VERSION
          value: 1.0.0
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: registry.lab.syscallx86.com/ovn-daemonset-fedora:latest
        imagePullPolicy: IfNotPresent
        name: ovs-metrics-exporter
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/dbus/
          name: host-var-run-dbus
          readOnly: true
        - mountPath: /var/log/openvswitch/
          name: host-var-log-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
          readOnly: true
      dnsPolicy: Default
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ovnkube-node
      serviceAccountName: ovnkube-node
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/run/dbus
          type: ""
        name: host-var-run-dbus
      - hostPath:
          path: /var/lib/kubelet
          type: ""
        name: host-kubelet
      - hostPath:
          path: /var/log/ovn-kubernetes
          type: ""
        name: host-var-log-ovnkube
      - hostPath:
          path: /var/run/ovn-kubernetes
          type: ""
        name: host-var-run-ovn-kubernetes
      - hostPath:
          path: /opt/cni/bin
          type: ""
        name: host-opt-cni-bin
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: host-etc-cni-netd
      - hostPath:
          path: /
          type: ""
        name: host-slash
      - hostPath:
          path: /var/run/netns
          type: ""
        name: host-netns
      - hostPath:
          path: /var/log/openvswitch
          type: ""
        name: host-var-log-ovs
      - hostPath:
          path: /run/openvswitch
          type: ""
        name: host-run-ovs
      - hostPath:
          path: /var/run/openvswitch
          type: ""
        name: host-var-run-ovs
      - hostPath:
          path: /etc/ovn
          type: DirectoryOrCreate
        name: host-ovn-cert
      - hostPath:
          path: /var/lib/openvswitch
          type: ""
        name: host-var-lib-ovs
      - hostPath:
          path: /etc/openvswitch
          type: ""
        name: host-etc-ovs
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 7
  desiredNumberScheduled: 7
  numberAvailable: 7
  numberMisscheduled: 0
  numberReady: 7
  observedGeneration: 2
  updatedNumberScheduled: 7
